# Generated by Django 5.0.7 on 2024-07-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_userfile_delete_codefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to='user_files/'),
        ),
    ]
